module Builder.Html where

import Prelude
import Reflex.Dom hiding (El, El, El_, link, button, select)


import Builder.Element
import Builder.Attribute

import Data.Text (Text)

htmlEl' :: Text -> El'
htmlEl' = makeElem Nothing

htmlEl :: Text -> El
htmlEl elemName props child = snd <$> makeElem Nothing elemName props child

htmlEl_ :: Text -> El_
htmlEl_ elemName props child = fst <$> makeElem Nothing elemName props child


head'       = htmlEl' "head"       :: El'
title'      = htmlEl' "title"      :: El'
base'       = htmlEl' "base"       :: El'
link'       = htmlEl' "link"       :: El'
meta'       = htmlEl' "meta"       :: El'
style'      = htmlEl' "style"      :: El'
script'     = htmlEl' "script"     :: El'
noscript'   = htmlEl' "noscript"   :: El'
body'       = htmlEl' "body"       :: El'
section'    = htmlEl' "section"    :: El'
nav'        = htmlEl' "nav"        :: El'
article'    = htmlEl' "article"    :: El'
aside'      = htmlEl' "aside"      :: El'
h1'         = htmlEl' "h1"         :: El'
h2'         = htmlEl' "h2"         :: El'
h3'         = htmlEl' "h3"         :: El'
h4'         = htmlEl' "h4"         :: El'
h5'         = htmlEl' "h5"         :: El'
h6'         = htmlEl' "h6"         :: El'
hgroup'     = htmlEl' "hgroup"     :: El'
header'     = htmlEl' "header"     :: El'
footer'     = htmlEl' "footer"     :: El'
address'    = htmlEl' "address"    :: El'
p'          = htmlEl' "p"          :: El'
hr'         = htmlEl' "hr"         :: El'
pre'        = htmlEl' "pre"        :: El'
blockquote' = htmlEl' "blockquote" :: El'
ol'         = htmlEl' "ol"         :: El'
ul'         = htmlEl' "ul"         :: El'
li'         = htmlEl' "li"         :: El'
dl'         = htmlEl' "dl"         :: El'
dt'         = htmlEl' "dt"         :: El'
dd'         = htmlEl' "dd"         :: El'
figure'     = htmlEl' "figure"     :: El'
figcaption' = htmlEl' "figcaption" :: El'
div'        = htmlEl' "div"        :: El'
a'          = htmlEl' "a"          :: El'
em'         = htmlEl' "em"         :: El'
strong'     = htmlEl' "strong"     :: El'
small'      = htmlEl' "small"      :: El'
s'          = htmlEl' "s"          :: El'
cite'       = htmlEl' "cite"       :: El'
q'          = htmlEl' "q"          :: El'
dfn'        = htmlEl' "dfn"        :: El'
abbr'       = htmlEl' "abbr"       :: El'
time'       = htmlEl' "time"       :: El'
code'       = htmlEl' "code"       :: El'
var'        = htmlEl' "var"        :: El'
samp'       = htmlEl' "samp"       :: El'
kbd'        = htmlEl' "kbd"        :: El'
sub'        = htmlEl' "sub"        :: El'
sup'        = htmlEl' "sup"        :: El'
i'          = htmlEl' "i"          :: El'
b'          = htmlEl' "b"          :: El'
u'          = htmlEl' "u"          :: El'
mark'       = htmlEl' "mark"       :: El'
ruby'       = htmlEl' "ruby"       :: El'
rt'         = htmlEl' "rt"         :: El'
rp'         = htmlEl' "rp"         :: El'
br'         = htmlEl' "br"         :: El'
bdi'        = htmlEl' "bdi"        :: El'
bdo'        = htmlEl' "bdo"        :: El'
span'       = htmlEl' "span"       :: El'
ins'        = htmlEl' "ins"        :: El'
del'        = htmlEl' "del"        :: El'
img'        = htmlEl' "img"        :: El'
iframe'     = htmlEl' "iframe"     :: El'
embed'      = htmlEl' "embed"      :: El'
object'     = htmlEl' "object"     :: El'
param'      = htmlEl' "param"      :: El'
video'      = htmlEl' "video"      :: El'
audio'      = htmlEl' "audio"      :: El'
source'     = htmlEl' "source"     :: El'
track'      = htmlEl' "track"      :: El'
canvas'     = htmlEl' "canvas"     :: El'
map'        = htmlEl' "map"        :: El'
area'       = htmlEl' "area"       :: El'
table'      = htmlEl' "table"      :: El'
caption'    = htmlEl' "caption"    :: El'
colgroup'   = htmlEl' "colgroup"   :: El'
col'        = htmlEl' "col"        :: El'
tbody'      = htmlEl' "tbody"      :: El'
thead'      = htmlEl' "thead"      :: El'
tfoot'      = htmlEl' "tfoot"      :: El'
tr'         = htmlEl' "tr"         :: El'
td'         = htmlEl' "td"         :: El'
th'         = htmlEl' "th"         :: El'
form'       = htmlEl' "form"       :: El'
fieldset'   = htmlEl' "fieldset"   :: El'
legend'     = htmlEl' "legend"     :: El'
label'      = htmlEl' "label"      :: El'
input'      = htmlEl' "input"      :: El'
button'     = htmlEl' "button"     :: El'
select'     = htmlEl' "select"     :: El'
datalist'   = htmlEl' "datalist"   :: El'
optgroup'   = htmlEl' "optgroup"   :: El'
option'     = htmlEl' "option"     :: El'
textarea'   = htmlEl' "textarea"   :: El'
keygen'     = htmlEl' "keygen"     :: El'
output'     = htmlEl' "output"     :: El'
progress'   = htmlEl' "progress"   :: El'
meter'      = htmlEl' "meter"      :: El'
details'    = htmlEl' "details"    :: El'
summary'    = htmlEl' "summary"    :: El'
command'    = htmlEl' "command"    :: El'
menu'       = htmlEl' "menu"       :: El'



head       = htmlEl "head"       :: El
title      = htmlEl "title"      :: El
base       = htmlEl "base"       :: El
link       = htmlEl "link"       :: El
meta       = htmlEl "meta"       :: El
style      = htmlEl "style"      :: El
script     = htmlEl "script"     :: El
noscript   = htmlEl "noscript"   :: El
body       = htmlEl "body"       :: El
section    = htmlEl "section"    :: El
nav        = htmlEl "nav"        :: El
article    = htmlEl "article"    :: El
aside      = htmlEl "aside"      :: El
h1         = htmlEl "h1"         :: El
h2         = htmlEl "h2"         :: El
h3         = htmlEl "h3"         :: El
h4         = htmlEl "h4"         :: El
h5         = htmlEl "h5"         :: El
h6         = htmlEl "h6"         :: El
hgroup     = htmlEl "hgroup"     :: El
header     = htmlEl "header"     :: El
footer     = htmlEl "footer"     :: El
address    = htmlEl "address"    :: El
p          = htmlEl "p"          :: El
hr         = htmlEl "hr"         :: El
pre        = htmlEl "pre"        :: El
blockquote = htmlEl "blockquote" :: El
ol         = htmlEl "ol"         :: El
ul         = htmlEl "ul"         :: El
li         = htmlEl "li"         :: El
dl         = htmlEl "dl"         :: El
dt         = htmlEl "dt"         :: El
dd         = htmlEl "dd"         :: El
figure     = htmlEl "figure"     :: El
figcaption = htmlEl "figcaption" :: El
div        = htmlEl "div"        :: El
a          = htmlEl "a"          :: El
em         = htmlEl "em"         :: El
strong     = htmlEl "strong"     :: El
small      = htmlEl "small"      :: El
s          = htmlEl "s"          :: El
cite       = htmlEl "cite"       :: El
q          = htmlEl "q"          :: El
dfn        = htmlEl "dfn"        :: El
abbr       = htmlEl "abbr"       :: El
time       = htmlEl "time"       :: El
code       = htmlEl "code"       :: El
var        = htmlEl "var"        :: El
samp       = htmlEl "samp"       :: El
kbd        = htmlEl "kbd"        :: El
sub        = htmlEl "sub"        :: El
sup        = htmlEl "sup"        :: El
i          = htmlEl "i"          :: El
b          = htmlEl "b"          :: El
u          = htmlEl "u"          :: El
mark       = htmlEl "mark"       :: El
ruby       = htmlEl "ruby"       :: El
rt         = htmlEl "rt"         :: El
rp         = htmlEl "rp"         :: El
br         = htmlEl "br"         :: El
bdi        = htmlEl "bdi"        :: El
bdo        = htmlEl "bdo"        :: El
span       = htmlEl "span"       :: El
ins        = htmlEl "ins"        :: El
del        = htmlEl "del"        :: El
img        = htmlEl "img"        :: El
iframe     = htmlEl "iframe"     :: El
embed      = htmlEl "embed"      :: El
object     = htmlEl "object"     :: El
param      = htmlEl "param"      :: El
video      = htmlEl "video"      :: El
audio      = htmlEl "audio"      :: El
source     = htmlEl "source"     :: El
track      = htmlEl "track"      :: El
canvas     = htmlEl "canvas"     :: El
map        = htmlEl "map"        :: El
area       = htmlEl "area"       :: El
table      = htmlEl "table"      :: El
caption    = htmlEl "caption"    :: El
colgroup   = htmlEl "colgroup"   :: El
col        = htmlEl "col"        :: El
tbody      = htmlEl "tbody"      :: El
thead      = htmlEl "thead"      :: El
tfoot      = htmlEl "tfoot"      :: El
tr         = htmlEl "tr"         :: El
td         = htmlEl "td"         :: El
th         = htmlEl "th"         :: El
form       = htmlEl "form"       :: El
fieldset   = htmlEl "fieldset"   :: El
legend     = htmlEl "legend"     :: El
label      = htmlEl "label"      :: El
input      = htmlEl "input"      :: El
button     = htmlEl "button"     :: El
select     = htmlEl "select"     :: El
datalist   = htmlEl "datalist"   :: El
optgroup   = htmlEl "optgroup"   :: El
option     = htmlEl "option"     :: El
textarea   = htmlEl "textarea"   :: El
keygen     = htmlEl "keygen"     :: El
output     = htmlEl "output"     :: El
progress   = htmlEl "progress"   :: El
meter      = htmlEl "meter"      :: El
details    = htmlEl "details"    :: El
summary    = htmlEl "summary"    :: El
command    = htmlEl "command"    :: El
menu       = htmlEl "menu"       :: El

head_       = htmlEl_ "head"       :: El_
-- title_      = htmlEl_ "title"      :: El_
base_       = htmlEl_ "base"       :: El_
link_       = htmlEl_ "link"       :: El_
meta_       = htmlEl_ "meta"       :: El_
--style_      = htmlEl_ "style"      :: El_
script_     = htmlEl_ "script"     :: El_
noscript_   = htmlEl_ "noscript"   :: El_
body_       = htmlEl_ "body"       :: El_
section_    = htmlEl_ "section"    :: El_
nav_        = htmlEl_ "nav"        :: El_
article_    = htmlEl_ "article"    :: El_
aside_      = htmlEl_ "aside"      :: El_
h1_         = htmlEl_ "h1"         :: El_
h2_         = htmlEl_ "h2"         :: El_
h3_         = htmlEl_ "h3"         :: El_
h4_         = htmlEl_ "h4"         :: El_
h5_         = htmlEl_ "h5"         :: El_
h6_         = htmlEl_ "h6"         :: El_
hgroup_     = htmlEl_ "hgroup"     :: El_
header_     = htmlEl_ "header"     :: El_
footer_     = htmlEl_ "footer"     :: El_
address_    = htmlEl_ "address"    :: El_
p_          = htmlEl_ "p"          :: El_
hr_         = htmlEl_ "hr"         :: El_
pre_        = htmlEl_ "pre"        :: El_
blockquote_ = htmlEl_ "blockquote" :: El_
ol_         = htmlEl_ "ol"         :: El_
ul_         = htmlEl_ "ul"         :: El_
li_         = htmlEl_ "li"         :: El_
dl_         = htmlEl_ "dl"         :: El_
dt_         = htmlEl_ "dt"         :: El_
dd_         = htmlEl_ "dd"         :: El_
figure_     = htmlEl_ "figure"     :: El_
figcaption_ = htmlEl_ "figcaption" :: El_
div_        = htmlEl_ "div"        :: El_
a_          = htmlEl_ "a"          :: El_
em_         = htmlEl_ "em"         :: El_
strong_     = htmlEl_ "strong"     :: El_
small_      = htmlEl_ "small"      :: El_
s_          = htmlEl_ "s"          :: El_
-- cite_       = htmlEl_ "cite"       :: El_
q_          = htmlEl_ "q"          :: El_
dfn_        = htmlEl_ "dfn"        :: El_
abbr_       = htmlEl_ "abbr"       :: El_
time_       = htmlEl_ "time"       :: El_
code_       = htmlEl_ "code"       :: El_
var_        = htmlEl_ "var"        :: El_
samp_       = htmlEl_ "samp"       :: El_
kbd_        = htmlEl_ "kbd"        :: El_
sub_        = htmlEl_ "sub"        :: El_
sup_        = htmlEl_ "sup"        :: El_
i_          = htmlEl_ "i"          :: El_
b_          = htmlEl_ "b"          :: El_
u_          = htmlEl_ "u"          :: El_
mark_       = htmlEl_ "mark"       :: El_
ruby_       = htmlEl_ "ruby"       :: El_
rt_         = htmlEl_ "rt"         :: El_
rp_         = htmlEl_ "rp"         :: El_
br_         = htmlEl_ "br"         :: El_
bdi_        = htmlEl_ "bdi"        :: El_
bdo_        = htmlEl_ "bdo"        :: El_
-- span_       = htmlEl_ "span"       :: El_
ins_        = htmlEl_ "ins"        :: El_
del_        = htmlEl_ "del"        :: El_
img_        = htmlEl_ "img"        :: El_
iframe_     = htmlEl_ "iframe"     :: El_
embed_      = htmlEl_ "embed"      :: El_
object_     = htmlEl_ "object"     :: El_
param_      = htmlEl_ "param"      :: El_
video_      = htmlEl_ "video"      :: El_
audio_      = htmlEl_ "audio"      :: El_
source_     = htmlEl_ "source"     :: El_
track_      = htmlEl_ "track"      :: El_
canvas_     = htmlEl_ "canvas"     :: El_
map_        = htmlEl_ "map"        :: El_
area_       = htmlEl_ "area"       :: El_
table_      = htmlEl_ "table"      :: El_
caption_    = htmlEl_ "caption"    :: El_
colgroup_   = htmlEl_ "colgroup"   :: El_
col_        = htmlEl_ "col"        :: El_
tbody_      = htmlEl_ "tbody"      :: El_
thead_      = htmlEl_ "thead"      :: El_
tfoot_      = htmlEl_ "tfoot"      :: El_
tr_         = htmlEl_ "tr"         :: El_
td_         = htmlEl_ "td"         :: El_
th_         = htmlEl_ "th"         :: El_
-- form_       = htmlEl_ "form"       :: El_
fieldset_   = htmlEl_ "fieldset"   :: El_
legend_     = htmlEl_ "legend"     :: El_
-- label_      = htmlEl_ "label"      :: El_
input_      = htmlEl_ "input"      :: El_
button_     = htmlEl_ "button"     :: El_
select_     = htmlEl_ "select"     :: El_
datalist_   = htmlEl_ "datalist"   :: El_
optgroup_   = htmlEl_ "optgroup"   :: El_
option_     = htmlEl_ "option"     :: El_
textarea_   = htmlEl_ "textarea"   :: El_
keygen_     = htmlEl_ "keygen"     :: El_
output_     = htmlEl_ "output"     :: El_
progress_   = htmlEl_ "progress"   :: El_
meter_      = htmlEl_ "meter"      :: El_
details_    = htmlEl_ "details"    :: El_
-- summary_    = htmlEl_ "summary"    :: El_
command_    = htmlEl_ "command"    :: El_
menu_       = htmlEl_ "menu"       :: El_



accept_          = commaListA "accept"               :: Attribute [Text]
accept_charset_  = spaceListA "accept-charset"       :: Attribute [Text]
accesskey_       = strA "accesskey"                  :: Attribute Text
align_           = strA "align"                      :: Attribute Text
action_          = strA "action"                     :: Attribute Text
alt_             = strA "alt"                        :: Attribute Text
async_           = boolA "async"                     :: Attribute Bool
autocomplete_    = ifA "on" "off" "autocomplete"     :: Attribute Bool -- False = "off", True = "on"
autofocus_       = boolA "autofocus"                 :: Attribute Bool
autoplay_        = boolA "autoplay"                  :: Attribute Bool
autosave_        = boolA "autosave"                  :: Attribute Bool
border_          = ifA "1" "" "border"               :: Attribute Bool   -- False = "", True = "1"
challenge_       = strA "challenge"                  :: Attribute Text
charset_         = strA "charset"                    :: Attribute Text
checked_         = boolA "checked"                   :: Attribute Bool
cite_            = strA "cite"                       :: Attribute Text
class_           = strA "class"                      :: Attribute Text
classes_           = spaceListA "class"              :: Attribute [Text]

cols_            = intA "cols"                       :: Attribute Int
colspan_         = intA "colspan"                    :: Attribute Int
content_         = strA "content"                    :: Attribute Text
contextmenu_     = strA "contextmenu"                :: Attribute Text
controls_        = boolA "controls"                  :: Attribute Bool
coords_          = commaSep $ intA "coords"          :: Attribute [Int]
data_            = strA "data"                       :: Attribute Text
datetime_        = strA "datetime"                   :: Attribute Text
default_         = boolA "default"                   :: Attribute Bool
defer_           = boolA "defer"                     :: Attribute Bool
dir_             = strA "dir"                        :: Attribute Text
dirname_         = strA "dirname"                    :: Attribute Text
disabled_        = boolA "disabled"                  :: Attribute Bool
draggable_       = ifA "true" "false" "draggable" :: Attribute Bool
dropzone_        = spaceListA "dropzone"             :: Attribute [Text]
enctype_         = strA "enctype"                    :: Attribute Text
for_             = strA "for"                        :: Attribute Text
form_            = strA "form"                       :: Attribute Text
formaction_      = strA "formaction"                 :: Attribute Text
formnovalidate_  = boolA "formaction"                :: Attribute Bool
headers_         = spaceListA "headers"              :: Attribute [Text]
height_          = intA "height"                     :: Attribute Int
hidden_          = boolA "hidden"                    :: Attribute Bool
high_            = floatA "high"                     :: Attribute Float
href_            = strA "href"                       :: Attribute Text
hreflang_        = strA "hreflang"                   :: Attribute Text
http_equiv       = strA "http-equiv"                 :: Attribute Text
icon_            = strA "icon"                       :: Attribute Text
id_              = strA "id"                         :: Attribute Text
ismap_           = boolA "ismap"                     :: Attribute Bool
itemprop_        = strA "itemprop"                   :: Attribute Text
keytype_         = strA "keytype"                    :: Attribute Text
kind_            = strA "kind"                       :: Attribute Text
label_           = strA "label"                      :: Attribute Text
lang_            = strA "lang"                       :: Attribute Text
list_            = strA "list"                       :: Attribute Text
loop_            = boolA "loop"                      :: Attribute Bool
low_             = floatA "low"                      :: Attribute Float
manifest_        = strA "manifest"                   :: Attribute Text
max_             = floatA "max"                      :: Attribute Float
maxlength_       = intA "maxlength"                  :: Attribute Int
media_           = strA "media"                      :: Attribute Text
method_          = strA "method"                     :: Attribute Text
min_             = floatA "min"                      :: Attribute Float
multiple_        = boolA "multiple"                  :: Attribute Bool
name_            = strA "name"                       :: Attribute Text
novalidate_      = boolA "novalidate"                :: Attribute Bool
open_            = boolA "open"                      :: Attribute Bool
optimum_         = floatA "optimum"                  :: Attribute Float
pattern_         = strA "pattern"                    :: Attribute Text
ping_            = strA "ping"                       :: Attribute Text
placeholder_     = strA "placeholder"                :: Attribute Text
poster_          = strA "poster"                     :: Attribute Text
preload_         = strA "preload"                    :: Attribute Text
radiogroup_      = strA "radiogroup"                 :: Attribute Text
readonly_        = boolA "readonly"                  :: Attribute Bool
rel_             = spaceListA "rel"                  :: Attribute [Text]
required_        = boolA "required"                  :: Attribute Bool
reversed_        = boolA "reversed"                  :: Attribute Bool
rows_            = intA "rows"                       :: Attribute Int
role_            = strA "role"                       :: Attribute Text
rowspan_         = intA "rowspan"                    :: Attribute Int
sandbox_         = spaceListA "sandbox"              :: Attribute [Text]
scope_           = strA "scope"                      :: Attribute Text
spellcheck_      = ifA "true" "false" "scope"     :: Attribute Bool
scoped_          = boolA "scoped"                    :: Attribute Bool
seamless_        = boolA "seamless"                  :: Attribute Bool
selected_        = boolA "selected"                  :: Attribute Bool
shape_           = strA "shape"                      :: Attribute Text
size_            = intA "size"                       :: Attribute Int
sizes_           = spaceListA "sizes"                :: Attribute [Text]
span_            = intA "span"                       :: Attribute Int
src_             = strA "src"                        :: Attribute Text
srcdoc_          = strA "srcdoc"                     :: Attribute Text
srclang_         = strA "srclang"                    :: Attribute Text
start_           = intA "start"                      :: Attribute Int
step_            = floatA "step"                     :: Attribute Float
style_           = styleA "style"                      :: Attribute [(Text, Text)]


summary_         = strA "summary"                    :: Attribute Text
tabindex_        = intA "tabindex"                   :: Attribute Int
target_          = strA "target"                     :: Attribute Text
title_           = strA "title"                      :: Attribute Text
type_            = strA "type"                       :: Attribute Text
usemap_          = strA "usemap"                     :: Attribute Text
value_           = strA "value"                      :: Attribute Text
width_           = intA "width"                      :: Attribute Int
wrap_            = strA "wrap"                       :: Attribute Text
